# Generated by Django 6.0.5 on 2026-05-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_channel', models.CharField(choices=[('email', 'Email'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('posters', 'Posters'), ('school_announcements', 'School announcements'), ('community_boards', 'Community boards'), ('website', 'Website'), ('newsletter', 'Newsletter')], max_length=40)),
                ('content_idea', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('asset_upload', models.FileField(blank=True, upload_to='promotion_assets/')),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_tasks', to='events.event')),
            ],
        ),
    ]
