# Generated by Django 6.0.5 on 2026-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_layout_notes', models.TextField(blank=True)),
                ('equipment_checklist', models.TextField(blank=True)),
                ('supply_inventory', models.TextField(blank=True)),
                ('transportation_plan', models.TextField(blank=True)),
                ('parking_notes', models.TextField(blank=True)),
                ('setup_schedule', models.TextField(blank=True)),
                ('cleanup_schedule', models.TextField(blank=True)),
                ('room_assignments', models.TextField(blank=True)),
                ('staff_assignments', models.TextField(blank=True)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_plan', to='events.event')),
            ],
        ),
    ]
