# Generated by Django 5.2.14 on 2026-05-13 14:19

import secrets
from django.db import migrations, models

ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def code(prefix):
    return f"{prefix}-" + ''.join(secrets.choice(ALPHABET) for _ in range(6))


def populate_codes(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    used = set(Event.objects.exclude(event_code__isnull=True).exclude(event_code='').values_list('event_code', flat=True))
    for event in Event.objects.filter(models.Q(event_code__isnull=True) | models.Q(event_code='')):
        value = code('EVT')
        while value in used:
            value = code('EVT')
        used.add(value)
        event.event_code = value
        event.save(update_fields=['event_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True),
        ),
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
