# Generated by Django 6.0.5 on 2026-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10),
        ),
    ]
