# Generated by Django 6.0.5 on 2026-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_repair_event_code_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
