# Generated by Django 5.2.14 on 2026-05-13 14:19

import secrets
from django.db import migrations, models

ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def code(prefix):
    return f"{prefix}-" + ''.join(secrets.choice(ALPHABET) for _ in range(6))


def populate_codes(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    used = set(Organization.objects.exclude(organization_code__isnull=True).exclude(organization_code='').values_list('organization_code', flat=True))
    for organization in Organization.objects.filter(models.Q(organization_code__isnull=True) | models.Q(organization_code='')):
        value = code('ORG')
        while value in used:
            value = code('ORG')
        used.add(value)
        organization.organization_code = value
        organization.save(update_fields=['organization_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
