# Generated by Django 6.0.5 on 2026-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_choice', models.CharField(blank=True, max_length=120)),
                ('side_choice', models.CharField(blank=True, max_length=120)),
                ('dessert_choice', models.CharField(blank=True, max_length=120)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('seat_choice', models.CharField(blank=True, max_length=80)),
                ('table_number', models.CharField(blank=True, max_length=40)),
                ('seat_me_with', models.CharField(blank=True, max_length=200)),
                ('accessibility_needs', models.TextField(blank=True)),
                ('drink_choice', models.CharField(blank=True, max_length=120)),
                ('gift_status', models.CharField(blank=True, max_length=120)),
                ('gift_note', models.TextField(blank=True)),
                ('custom_answers', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='guests.guest')),
            ],
        ),
    ]
