# Generated by Django 6.0.5 on 2026-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('access_type', models.CharField(default='General', max_length=80)),
                ('invite_status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('opened', 'Opened'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('expired', 'Expired'), ('checked_in', 'Checked in')], default='draft', max_length=30)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('declining', 'Declining'), ('maybe', 'Maybe')], default='pending', max_length=30)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
