# Generated by Django 6.0.5 on 2026-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_events', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
