# Generated by Django 6.0.5 on 2026-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('contacted', 'Contacted'), ('quote_received', 'Quote received'), ('selected', 'Selected'), ('contract_sent', 'Contract sent'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('completed', 'Completed')], default='researching', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='events.event')),
            ],
        ),
    ]
