# Generated by Django 6.0.5 on 2026-05-13 13:07

import access.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(default=access.models.generate_access_code, max_length=48, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('active', models.BooleanField(default=True)),
                ('confirmation_status', models.CharField(default='confirmed', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_card', to='guests.guest')),
            ],
        ),
    ]
