# Generated by Django 6.0.5 on 2026-05-13 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContingencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weather', 'Weather'), ('vendor_cancellation', 'Vendor cancellation'), ('low_attendance', 'Low attendance'), ('budget_overrun', 'Budget overrun'), ('equipment_failure', 'Equipment failure'), ('transportation_delay', 'Transportation delay'), ('staff_shortage', 'Staff shortage'), ('technical_issue', 'Technical issue'), ('venue_problem', 'Venue problem')], max_length=40)),
                ('probability', models.PositiveSmallIntegerField(default=1)),
                ('impact', models.PositiveSmallIntegerField(default=1)),
                ('backup_plan', models.TextField()),
                ('trigger_point', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='open', max_length=40)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingency_plans', to='events.event')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
