# Generated by Django 6.0.5 on 2026-05-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_guest_confirmed', models.BooleanField(default=False)),
                ('notify_on_guest_arrived', models.BooleanField(default=False)),
                ('include_menu', models.BooleanField(default=False)),
                ('include_seat', models.BooleanField(default=False)),
                ('include_drinks', models.BooleanField(default=False)),
                ('include_gift', models.BooleanField(default=False)),
                ('include_custom_answers', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='events.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard')], default='email', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='events.event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.guest')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.vendornotificationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
